Controllers/FlightsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcFlight.Data;
using MvcFlight.Models;

namespace dotnet_flights_mvc.Controllers
{
    public class FlightsController : Controller
    {
        private readonly MvcFlightContext _context;

        public FlightsController(MvcFlightContext context)
        {
            _context = context;
        }

        // GET: Flights
        // to search by passenger in the future pass a flightPassenger string
        public async  Task<IActionResult> Index(string flightAirport, string searchString)
        {
            if(_context.Flights == null)
            {
                return Problem("Entity set'MvcFlight.Context.Flight' is null.");
            }
            // Use LINQ to get list of airports
            IQueryable<string> airportQuery = from m in _context.Flights
                                                orderby m.Airport
                                                select m.Airport;
            var flights = from m in _context.Flights
                            .Include(f => f.Tickets)
                            select m;

            if (!string.IsNullOrEmpty(searchString))
            {
                flights = flights.Where(s => s.Airline!.ToUpper().Contains(searchString.ToUpper()));
            }

            if (!string.IsNullOrEmpty(flightAirport))
            {
                flights = flights.Where(x => x.Airport == flightAirport);
            }

            var flightAirportVM = new FlightAirportViewModel
            {
                Airports = new SelectList(await airportQuery.Distinct().ToListAsync()),
                Flights = await flights.ToListAsync()
            };

            return View(flightAirportVM);
        }

        // GET: Flights/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flight = await _context.Flights
                .Include(f => f.Tickets)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (flight == null)
            {
                return NotFound();
            }

            return View(flight);
        }

        // GET: Flights/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Flights/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Airline,Departs,Airport,FlightNo,Ticket")] Flight flight)
        {
            if (ModelState.IsValid)
            {
                _context.Add(flight);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(flight);
        }

        // GET: Flights/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flight = await _context.Flights.FindAsync(id);
            if (flight == null)
            {
                return NotFound();
            }
            return View(flight);
        }

        // POST: Flights/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Airline,Departs,Airport,FlightNo,Ticket")] Flight flight)
        {
            if (id != flight.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(flight);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FlightExists(flight.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(flight);
        }

        // GET: Flights/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flight = await _context.Flights
                .FirstOrDefaultAsync(m => m.Id == id);
            if (flight == null)
            {
                return NotFound();
            }

            return View(flight);
        }

        // POST: Flights/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var flight = await _context.Flights.FindAsync(id);
            if (flight != null)
            {
                _context.Flights.Remove(flight);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FlightExists(int id)
        {
            return _context.Flights.Any(e => e.Id == id);
        }


        // // GET: Flights/NewTicket/5
        // public async Task<IActionResult> NewTicket(int? flightId)
        // {
        //     // get the flight
        //     var flight = await _context.Flight
        //         .Include(f => f.Tickets)
        //         .FirstOrDefaultAsync(m => m.Id == flightId);

        //     if (flight == null)
        //     {
        //         return NotFound();
        //     }

        //     var newTicket = new Ticket
        //     {
        //         FlightId = flight.Id,
        //         Seat = "",
        //     };

        //     ViewBag.flightId = flight.Id;
        //     ViewBag.Airline = flight.Airline;
        //     ViewBag.FlightNo = flight.FlightNo;
            
        //     return View(newTicket);
        // }


        // POST: Flights/CreateTicket/:id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateTicket(int flightId, [Bind("Id,Seat,Price")] Ticket ticket)
        {
            
            var flight = await _context.Flights
                .Include(f => f.Tickets)
                .FirstOrDefaultAsync(m => m.Id == flightId);

            if (flight == null)
            {
                return NotFound();
            }

            
            if (ModelState.IsValid)
            {
                _context.Add(ticket);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(flight);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FlightsDOTNet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/dotnet_flights_mvc.styles.css" asp-append-version="true" />
</head>
<body class="d-flex flex-column min-vh-100 bg-dark text-light">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-black border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">FlightsDOTNet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Flights" asp-action="Index">Flights</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-light h-10 mt-auto bg-black">
        <div class="container">
            &copy; 2024 - Flights Dot Net - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>